# Generated by Django 5.2.1 on 2025-11-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='domains',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sender_emails',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sender_name',
        ),
    ]
